config/routes.rb
Rails.application.routes.draw do
  root 'site#index'
  get 'new_horizontal_customer' => 'customers#new_horizontal'
  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  end
  
  def new
    @new_customer=  Customer.new
  end
  
  def new_horizontal
    
    @new_customer = Customer.new
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/customers/backup_new.html.erb
<%= simple_form_for @new_customer do |f| %>
<%= f.input :name, label: 'Your username please', wrapper_html: { class: 'col-lg-3' } %>
<%= f.input :email, hint: 'No special characters.' %>
<%= f.input :description, placeholder: 'user@domain.com' %> 
  <%= f.button :submit %>
<% end %>

<%= simple_form_for @new_customer do |f| %>

  <div class="important-info form row">
    <div class="col-lg-3">
      <label class="control-label">
      * Customer
      </label>
      <div class="input-group customer">
        <select class="select optional newclass selectpicker form-control" id="transaction_person_id" name="transaction[person_id]">
          <option value="2167">Adam noviria (Customer)</option>
          <option value="2280">BMB (Customer)</option>
          <option value="2140">hahaha (Customer)</option>
          <option value="2141">hjajaja (Customer)</option>
        </select>
        <span class="input-group-btn">
        <button class="btn btn-md" data-target="#add-customer" data-toggle="modal" id="btn-add-new-customer">
        <i class="fa fa-plus"></i>
        </button>
        </span>
      </div>
    </div>






<!--     <div class="col-lg-3">
      <label class="control-label">
      Email
      </label>
      <input class="string email optional form-control form-control"
             id="transaction_email" name="transaction[email]" type="email">
    </div> -->
    <%= f.input :name, label: 'Email', wrapper_html: { class: 'col-lg-3' } %>


    <div class="col-lg-6 total-amount" style="text-align: right;">
      <h2>
        Total
        <span id="header_amount">Rp. 0,00</span>
      </h2>
    </div>
  </div>







  <div class="invoice-details row">
    <%= f.input :description, label: 'Billing Address', wrapper_html: { class: 'col-lg-3' } %>
    <div class="col-lg-2">
      <div class="payment-terms">
        <%= f.input :transaction_date, label: 'Transaction Date', :as => :string, input_html: { class: 'date-picker' }  %>
        
<!--       <div class="form-group">
        <label class="control-label">
        Transaction Date
        </label>
        <div class="input-group date" data-date-format="dd/mm/yyyy">
          <span class="input-group-addon custom">
            <i class="fa fa-calendar"></i>
          </span>
          <input class="string required form-control form-control date-picker" id="transaction_transaction_date" name="transaction[transaction_date]" type="text" value="12/05/2015">
        </div>
      </div> -->
      <!-- Transaction Due Date -->
        
        
<!--       <div class="form-group">
        <label class="control-label">
        Due Date
        </label>
        <div class="input-group date" data-date-format="dd/mm/yyyy">
          <span class="input-group-addon custom">
            <i class="fa fa-calendar"></i>
          </span>
          <input class="string optional form-control form-control date-picker" id="transaction_due_date" name="transaction[due_date]" type="text" value="11/06/2015">
        </div>
      </div> -->
      <!-- Shipping Date -->
        
        <%= f.input :due_date, label: 'Due Date', :as => :string , input_html: { class: 'date-picker' }  %>
      </div>
    </div>





    <!-- THIRD COLUMN - SHIPPING -->
    <div class="col-lg-2">
      <div class="shipping-method">
      <!-- Terms of Payment -->
        <div class="form-group">
          <label class="control-label">
          Term
          </label>
          <div class="input-group">
            <select class="select optional newclass form-control selectpicker form-control" id="transaction_term_id" name="transaction[term_id]">
              <option value="1366">Cash on Delivery</option>
              <option value="1367">Net 15</option>
              <option selected="selected" value="1368">Net 30</option>
              <option value="1369">Net 60</option>
            </select>
            <span class="input-group-btn">
              <button class="btn btn-md" data-target="#add-term" data-toggle="modal" id="btn-add-new-term">
                <i class="fa fa-plus"></i>
              </button>
            </span>
          </div>
        </div>
      </div>
    </div>
  <!-- Rightmost column -->
    <div class="col-lg-2">
      <div class="transaction-ref">
        <div class="form-group">
          <label class="control-label">
          Transaction No
          </label>
          <input class="string optional form-control form-control" id="transaction_transaction_no" name="transaction[transaction_no]" type="text" value="10006">
        <!-- Ref Number -->
        </div>

        <div class="form-group">
          <label class="control-label">
          Customer Ref No
          </label>
          <input class="string optional form-control form-control" id="transaction_reference_no" name="transaction[reference_no]" type="text">
        </div>
      </div>
    </div>

    <div class="col-lg-2">
    </div>


  </div>

  <div class="action-group">
    <div class="col-md-12 text-right">
      <a class="btn btn-danger" href="/transactions/invoice/index">
        <i class="fa fa-close"></i>
        Cancel
      </a>
      <button class="btn btn-success" data-disable-with="Processing..." id="create_invoice" 
              name="button" type="button" wrapper="false">Create Invoice</button>
    </div>
  </div>
<% end %>


<% content_for :page_specific_js do %>
  <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  <!-- DONE -->
  <%= javascript_include_tag  'clipone/bootstrap-datepicker'   %>

		<script>
			jQuery(document).ready(function() {
				Main.init();
        
        $('.date-picker').datepicker({
            autoclose: true
        });
			});
		</script>
<% end %>




<% content_for :page_specific_css do %>
  <%= stylesheet_link_tag "clipone/datepicker" %>
<% end %>

app/views/customers/new_horizontal.html.erb
<%= simple_form_for @new_customer, url: new_horizontal_customer_url, as: 'user_horizontal', html: { class: 'form-horizontal' , :style => "width:50%;" },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, placeholder: 'Email', :label_html => {:class => "col-sm-2"} %>

  <%= f.input :email, placeholder: 'Password', :label_html => {:class => "col-sm-2"} %>
  <%= f.input :description, placeholder: 'Description', :label_html => {:class => "col-sm-2"} %> 
<%= f.input  :due_date,  input_html: { class: 'date-picker' }, :as => :string, :label_html => {:class => "col-sm-2"} %> 

 
<div class="row action-group">
  <div class="col-lg-6 col-sm-push-2">
    <a class="btn btn-danger" href="/accounts/chart_of_accounts">
    Cancel
    </a> 
    <%= f.button :submit ,:class => "btn-action btn btn-success"   %>
  </div>
</div>


  
<% end %>

 


<% content_for :page_specific_js do %>
  <%= javascript_include_tag  'clipone/bootstrap-datepicker'   %>

		<script>
			jQuery(document).ready(function() {
				Main.init();
        
        $('.date-picker').datepicker({
            autoclose: true
        });
			});
		</script>
<% end %>




<% content_for :page_specific_css do %>
  <%= stylesheet_link_tag "clipone/datepicker" %>
<% end %>

app/views/layouts/_content_header.html.erb
<!-- start: PAGE HEADER -->
<div class="row">
  <div class="col-sm-12">

    <!-- start: PAGE TITLE & BREADCRUMB -->
    <ol class="breadcrumb">
      <li>
        <i class="clip-home-3"></i>
        <a href="#">
          Home
        </a>
      </li>
      <li class="active">
        Dashboard
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>Dashboard <small>overview &amp; stats </small></h1>
    </div>
    <!-- end: PAGE TITLE & BREADCRUMB -->
  </div>
</div>
<!-- end: PAGE HEADER -->

app/views/layouts/_footer.html.erb
<!-- start: FOOTER -->

<div class="footer clearfix">
  <div class="footer-inner">
    2014 &copy; RePay. Reimburse made simple.
  </div>
  <div class="footer-items">
    <span class="go-top"><i class="clip-chevron-up"></i></span>
  </div>
</div>
<!-- end: FOOTER -->

app/views/layouts/_javascript.html.erb
<!--[if lt IE 9]>
<script src="assets/plugins/respond.min.js"></script>
<script src="assets/plugins/excanvas.min.js"></script>
<script type="text/javascript" src="assets/plugins/jQuery-lib/1.10.2/jquery.min.js"></script>
<![endif]-->
<!--[if gte IE 9]><!-->
<!-- DONE -->
<!-- 		<script src="assets/plugins/jQuery-lib/2.0.3/jquery.min.js"></script> -->
<!--<![endif]-->
<!-- DONE -->
<!-- 		<script src="assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script> -->
<!-- DONE -->
<!-- 		<script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script> -->
<!-- DONE -->
<!-- 		<script src="assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script> -->
<!-- DONE -->
<!-- 		<script src="assets/plugins/blockUI/jquery.blockUI.js"></script> -->
<!-- 		<script src="assets/plugins/iCheck/jquery.icheck.min.js"></script> -->
<!--  DONE -->
<!-- 		<script src="assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script> -->
<!-- DONE -->
<!-- 		<script src="assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script> -->
<!-- DONE -->
<!-- 		<script src="assets/plugins/less/less-1.5.0.min.js"></script> -->
<!-- DONE -->
<!-- 		<script src="assets/plugins/jquery-cookie/jquery.cookie.js"></script> -->
<!-- DONe -->
<!-- 		<script src="assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js"></script> -->

<!-- DONE -->
<!-- 		<script src="assets/js/main.js"></script> -->
<%= javascript_include_tag 'application'  %>
<!-- end: MAIN JAVASCRIPTS -->

<%= yield :page_specific_js %>

app/views/layouts/_page_header.html.erb
<!-- start: PAGE HEADER -->
<div class="row">
  <div class="col-sm-12">

    <!-- start: PAGE TITLE & BREADCRUMB -->
    <ol class="breadcrumb">
      <li>
        <i class="clip-home-3"></i>
        <a href="#">
          Home
        </a>
      </li>
      <li class="active">
        Dashboard
      </li>
      <li class="search-box">
        <form class="sidebar-search">
          <div class="form-group">
            <input type="text" placeholder="Start Searching...">
            <button class="submit">
              <i class="clip-search-3"></i>
            </button>
          </div>
        </form>
      </li>
    </ol>
    <div class="page-header">
      <h1>Dashboard <small>overview &amp; stats </small></h1>
    </div>
    <!-- end: PAGE TITLE & BREADCRUMB -->
  </div>
</div>
<!-- end: PAGE HEADER -->

app/views/layouts/_sidebar.html.erb
<!-- start: SIDEBAR -->
<div class="main-navigation navbar-collapse collapse">
  <!-- start: MAIN MENU TOGGLER BUTTON -->
  <div class="navigation-toggler">
    <i class="clip-chevron-left"></i>
    <i class="clip-chevron-right"></i>
  </div>
  <!-- end: MAIN MENU TOGGLER BUTTON -->
  <!-- start: MAIN NAVIGATION MENU -->

  <ul class="main-navigation-menu">
    <li class="active open">
      <%= link_to root_url do %>
        <i class="clip-home-3"></i>
        <span class="title"> Dashboard </span><span class="selected"></span>
      <% end %>
<!--       <a href="index.html">
      </a> -->
    </li>
    <li>
      <%= link_to new_customer_url do %>
        <i class="clip-screen"></i>
        <span class="title"> New Customer </span><i class="icon-arrow"></i>
        <span class="selected"></span>
      <% end %>
      
    </li>
    
    <li>
      <%= link_to new_horizontal_customer_url do %>
        <i class="clip-screen"></i>
        <span class="title"> Horizontal Customer </span><i class="icon-arrow"></i>
        <span class="selected"></span>
      <% end %>
      
    </li>
    
    
    <li>
      
      
      <%= link_to customers_url do %>
        <i class="clip-cursor"></i>
        <span class="title"> Customers</span><span class="selected"></span>
      <% end %>
<!--       <a href="../../frontend/clip-one/index.html" target="_blank">
      </a> -->
    </li>
    <li>
      <a href="javascript:void(0)"><i class="clip-cog-2"></i>
        <span class="title"> UI Lab </span><i class="icon-arrow"></i>
        <span class="selected"></span>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="ui_elements.html">
            <span class="title"> Elements </span>
          </a>
        </li>
        <li>
          <a href="ui_buttons.html">
            <span class="title"> Buttons &amp; icons </span>
          </a>
        </li>
        <li>
          <a href="ui_animations.html">
            <span class="title"> CSS3 Animation </span>
          </a>
        </li>
        <li>
          <a href="ui_modals.html">
            <span class="title"> Extended Modals </span>
          </a>
        </li>
        <li>
          <a href="ui_tabs_accordions.html">
            <span class="title"> Tabs &amp; Accordions </span>
          </a>
        </li>
        <li>
          <a href="ui_sliders.html">
            <span class="title"> Sliders </span>
          </a>
        </li>
        <li>
          <a href="ui_treeview.html">
            <span class="title"> Treeview </span>
          </a>
        </li>
        <li>
          <a href="ui_nestable.html">
            <span class="title"> Nestable List </span>
          </a>
        </li>
        <li>
          <a href="ui_typography.html">
            <span class="title"> Typography </span>
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)"><i class="clip-grid-6"></i>
        <span class="title"> Tables </span><i class="icon-arrow"></i>
        <span class="selected"></span>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="table_static.html">
            <span class="title">Static Tables</span>
          </a>
        </li>
        <li>
          <a href="table_responsive.html">
            <span class="title">Responsive Tables</span>
          </a>
        </li>
        <li>
          <a href="table_data.html">
            <span class="title">Data Tables</span>
          </a>
        </li>
        <li>
          <a href="table_export.html">
            <span class="title">Table Export</span>
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)"><i class="clip-pencil"></i>
        <span class="title"> Forms </span><i class="icon-arrow"></i>
        <span class="selected"></span>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="form_elements.html">
            <span class="title">Form Elements</span>
          </a>
        </li>
        <li>
          <a href="form_wizard.html">
            <span class="title">Form Wizard</span>
          </a>
        </li>
        <li>
          <a href="form_validation.html">
            <span class="title">Form Validation</span>
          </a>
        </li>
        <li>
          <a href="form_inline.html">
            <span class="title">Inline Editor</span>
          </a>
        </li>
        <li>
          <a href="form_x_editable.html">
            <span class="title">Form X-editable</span>
          </a>
        </li>
        <li>
          <a href="form_image_cropping.html">
            <span class="title">Image Cropping</span>
          </a>
        </li>
        <li>
          <a href="form_multiple_upload.html">
            <span class="title">Multiple File Upload</span>
          </a>
        </li>
        <li>
          <a href="form_dropzone.html">
            <span class="title">Dropzone File Upload</span>
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)"><i class="clip-user-2"></i>
        <span class="title">Login</span><i class="icon-arrow"></i>
        <span class="selected"></span>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="login_example1.html">
            <span class="title">Login Form Example 1</span>
          </a>
        </li>
        <li>
          <a href="login_example2.html">
            <span class="title">Login Form Example 2</span>
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)"><i class="clip-file"></i>
        <span class="title">Pages</span><i class="icon-arrow"></i>
        <span class="selected"></span>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="pages_user_profile.html">
            <span class="title">User Profile</span>
          </a>
        </li>
        <li>
          <a href="pages_invoice.html">
            <span class="title">Invoice</span>
            <span class="badge badge-new">new</span>
          </a>
        </li>
        <li>
          <a href="pages_gallery.html">
            <span class="title">Gallery</span>
          </a>
        </li>
        <li>
          <a href="pages_timeline.html">
            <span class="title">Timeline</span>
          </a>
        </li>
        <li>
          <a href="pages_calendar.html">
            <span class="title">Calendar</span>
          </a>
        </li>
        <li>
          <a href="pages_messages.html">
            <span class="title">Messages</span>
          </a>
        </li>
        <li>
          <a href="pages_blank_page.html">
            <span class="title">Blank Page</span>
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)"><i class="clip-attachment-2"></i>
        <span class="title">Utility</span><i class="icon-arrow"></i>
        <span class="selected"></span>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="utility_faq.html">
            <span class="title">Faq</span>
          </a>
        </li>
        <li>
          <a href="utility_search_result.html">
            <span class="title">Search Results </span>
            <span class="badge badge-new">new</span>
          </a>
        </li>
        <li>
          <a href="utility_lock_screen.html">
            <span class="title">Lock Screen</span>
          </a>
        </li>
        <li>
          <a href="utility_404_example1.html">
            <span class="title">Error 404 Example 1</span>
          </a>
        </li>
        <li>
          <a href="utility_404_example2.html">
            <span class="title">Error 404 Example 2</span>
          </a>
        </li>
        <li>
          <a href="utility_404_example3.html">
            <span class="title">Error 404 Example 3</span>
          </a>
        </li>
        <li>
          <a href="utility_500_example1.html">
            <span class="title">Error 500 Example 1</span>
          </a>
        </li>
        <li>
          <a href="utility_500_example2.html">
            <span class="title">Error 500 Example 2</span>
          </a>
        </li>
        <li>
          <a href="utility_pricing_table.html">
            <span class="title">Pricing Table</span>
          </a>
        </li>
        <li>
          <a href="utility_coming_soon.html">
            <span class="title">Cooming Soon</span>
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:;" class="active">
        <i class="clip-folder"></i>
        <span class="title"> 3 Level Menu </span>
        <i class="icon-arrow"></i>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="javascript:;">
            Item 1 <i class="icon-arrow"></i>
          </a>
          <ul class="sub-menu">
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 2
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 3
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:;">
            Item 1 <i class="icon-arrow"></i>
          </a>
          <ul class="sub-menu">
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#">
            Item 3
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:;">
        <i class="clip-folder-open"></i>
        <span class="title"> 4 Level Menu </span><i class="icon-arrow"></i>
        <span class="arrow "></span>
      </a>
      <ul class="sub-menu">
        <li>
          <a href="javascript:;">
            Item 1 <i class="icon-arrow"></i>
          </a>
          <ul class="sub-menu">
            <li>
              <a href="javascript:;">
                Sample Link 1 <i class="icon-arrow"></i>
              </a>
              <ul class="sub-menu">
                <li>
                  <a href="#"><i class="fa fa-times"></i>
                    Sample Link 1</a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-pencil"></i>
                    Sample Link 1</a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-edit"></i>
                    Sample Link 1</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 2
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 3
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:;">
            Item 2 <i class="icon-arrow"></i>
          </a>
          <ul class="sub-menu">
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
            <li>
              <a href="#">
                Sample Link 1
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#">
            Item 3
          </a>
        </li>
      </ul>
    </li>
    <li>
      <a href="maps.html"><i class="clip-location"></i>
        <span class="title">Maps</span>
        <span class="selected"></span>
      </a>
    </li>
    <li>
      <a href="charts.html"><i class="clip-bars"></i>
        <span class="title">Charts</span>
        <span class="selected"></span>
      </a>
    </li>
  </ul>
  <!-- end: MAIN NAVIGATION MENU -->
</div>
<!-- end: SIDEBAR -->

app/views/layouts/_style_selector.html.erb
<!-- start: STYLE SELECTOR BOX -->
<div id="style_selector" class="hidden-xs">
  <div id="style_selector_container" style="display:block">
    <div class="style-main-title">
      Style Selector
    </div>
    <div class="box-title">
      Choose Your Layout Style
    </div>
    <div class="input-box">
      <div class="input">
        <select name="layout">
          <option value="default">Wide</option><option value="boxed">Boxed</option>
        </select>
      </div>
    </div>
    <div class="box-title">
      Choose Your Header Style
    </div>
    <div class="input-box">
      <div class="input">
        <select name="header">
          <option value="fixed">Fixed</option><option value="default">Default</option>
        </select>
      </div>
    </div>
    <div class="box-title">
      Choose Your Footer Style
    </div>
    <div class="input-box">
      <div class="input">
        <select name="footer">
          <option value="default">Default</option><option value="fixed">Fixed</option>
        </select>
      </div>
    </div>
    <div class="box-title">
      Backgrounds for Boxed Version
    </div>
    <div class="images boxed-patterns">
      <a id="bg_style_1" href="#">
<!--                       <img alt="" src="assets/images/bg.png"> -->
        <%= image_tag "clipone/bg.png" %>
      </a>
      <a id="bg_style_2" href="#">
<!--                       <img alt="" src="assets/images/bg_2.png"> -->
        <%= image_tag "clipone/bg_2.png" %>
      </a>
      <a id="bg_style_3" href="#">
<!--                       <img alt="" src="assets/images/bg_3.png"> -->
        <%= image_tag "clipone/bg_3.png" %>
      </a>
      <a id="bg_style_4" href="#">
<!--                       <img alt="" src="assets/images/bg_4.png"> -->
        <%= image_tag "clipone/bg_4.png" %>
      </a>
      <a id="bg_style_5" href="#">
<!--                       <img alt="" src="assets/images/bg_5.png"> -->
        <%= image_tag "clipone/bg_2.png" %>
      </a>
    </div>
    <div class="box-title">
      5 Predefined Color Schemes
    </div>
    <div class="images icons-color">
      <a id="light" href="#">
<!--                       <img class="active" alt="" src="assets/images/lightgrey.png"> -->
        <%= image_tag "clipone/lightgrey.png" %>
      </a>
      <a id="dark" href="#">
        <%= image_tag "clipone/darkgrey.png" %>
      </a>
      <a id="black_and_white" href="#">
        <%= image_tag "clipone/blackandwhite.png" %>
      </a>
      <a id="navy" href="#">
        <%= image_tag "clipone/navy.png" %>
      </a>
      <a id="green" href="#">
        <%= image_tag "clipone/navy.png" %>
      </a>
    </div>
    <div class="box-title">
      Style it with LESS
    </div>
    <div class="images">
      <div class="form-group">
        <label>
          Basic
        </label>
        <input type="text" value="#ffffff" class="color-base">
        <div class="dropdown">
          <a class="add-on dropdown-toggle" data-toggle="dropdown"><i style="background-color: #ffffff"></i></a>
          <ul class="dropdown-menu pull-right">
            <li>
              <div class="colorpalette"></div>
            </li>
          </ul>
        </div>
      </div>
      <div class="form-group">
        <label>
          Text
        </label>
        <input type="text" value="#555555" class="color-text">
        <div class="dropdown">
          <a class="add-on dropdown-toggle" data-toggle="dropdown"><i style="background-color: #555555"></i></a>
          <ul class="dropdown-menu pull-right">
            <li>
              <div class="colorpalette"></div>
            </li>
          </ul>
        </div>
      </div>
      <div class="form-group">
        <label>
          Elements
        </label>
        <input type="text" value="#007AFF" class="color-badge">
        <div class="dropdown">
          <a class="add-on dropdown-toggle" data-toggle="dropdown"><i style="background-color: #007AFF"></i></a>
          <ul class="dropdown-menu pull-right">
            <li>
              <div class="colorpalette"></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div style="height:25px;line-height:25px; text-align: center">
      <a class="clear_style" href="#">
        Clear Styles
      </a>
      <a class="save_style" href="#">
        Save Styles
      </a>
    </div>
  </div>
  <div class="style-toggle open"></div>
</div>
<!-- end: STYLE SELECTOR BOX -->

app/views/layouts/application_sample.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntegrateWrapbootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>